#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaControlador
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="P2AYD1")]
	public partial class db_entityDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertUSUARO(USUARO instance);
    partial void UpdateUSUARO(USUARO instance);
    partial void DeleteUSUARO(USUARO instance);
    partial void InsertCUENTA(CUENTA instance);
    partial void UpdateCUENTA(CUENTA instance);
    partial void DeleteCUENTA(CUENTA instance);
    #endregion
		
		public db_entityDataContext() : 
				base(global::CapaControlador.Properties.Settings.Default.P2AYD1ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public db_entityDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public db_entityDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public db_entityDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public db_entityDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<USUARO> USUARO
		{
			get
			{
				return this.GetTable<USUARO>();
			}
		}
		
		public System.Data.Linq.Table<CUENTA> CUENTA
		{
			get
			{
				return this.GetTable<CUENTA>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.USUARO")]
	public partial class USUARO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _NOMBRECOMPLETO;
		
		private string _USERNAME;
		
		private string _EMAIL;
		
		private string _CLAVE;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNOMBRECOMPLETOChanging(string value);
    partial void OnNOMBRECOMPLETOChanged();
    partial void OnUSERNAMEChanging(string value);
    partial void OnUSERNAMEChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnCLAVEChanging(string value);
    partial void OnCLAVEChanged();
    #endregion
		
		public USUARO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRECOMPLETO", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string NOMBRECOMPLETO
		{
			get
			{
				return this._NOMBRECOMPLETO;
			}
			set
			{
				if ((this._NOMBRECOMPLETO != value))
				{
					this.OnNOMBRECOMPLETOChanging(value);
					this.SendPropertyChanging();
					this._NOMBRECOMPLETO = value;
					this.SendPropertyChanged("NOMBRECOMPLETO");
					this.OnNOMBRECOMPLETOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="VarChar(200) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string USERNAME
		{
			get
			{
				return this._USERNAME;
			}
			set
			{
				if ((this._USERNAME != value))
				{
					this.OnUSERNAMEChanging(value);
					this.SendPropertyChanging();
					this._USERNAME = value;
					this.SendPropertyChanged("USERNAME");
					this.OnUSERNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLAVE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CLAVE
		{
			get
			{
				return this._CLAVE;
			}
			set
			{
				if ((this._CLAVE != value))
				{
					this.OnCLAVEChanging(value);
					this.SendPropertyChanging();
					this._CLAVE = value;
					this.SendPropertyChanged("CLAVE");
					this.OnCLAVEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CUENTA")]
	public partial class CUENTA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _NUMEROCUENTA;
		
		private int _TIPO;
		
		private decimal _BALANCE;
		
		private string _USERNAME;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNUMEROCUENTAChanging(int value);
    partial void OnNUMEROCUENTAChanged();
    partial void OnTIPOChanging(int value);
    partial void OnTIPOChanged();
    partial void OnBALANCEChanging(decimal value);
    partial void OnBALANCEChanged();
    partial void OnUSERNAMEChanging(string value);
    partial void OnUSERNAMEChanged();
    #endregion
		
		public CUENTA()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUMEROCUENTA", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int NUMEROCUENTA
		{
			get
			{
				return this._NUMEROCUENTA;
			}
			set
			{
				if ((this._NUMEROCUENTA != value))
				{
					this.OnNUMEROCUENTAChanging(value);
					this.SendPropertyChanging();
					this._NUMEROCUENTA = value;
					this.SendPropertyChanged("NUMEROCUENTA");
					this.OnNUMEROCUENTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPO", DbType="Int NOT NULL")]
		public int TIPO
		{
			get
			{
				return this._TIPO;
			}
			set
			{
				if ((this._TIPO != value))
				{
					this.OnTIPOChanging(value);
					this.SendPropertyChanging();
					this._TIPO = value;
					this.SendPropertyChanged("TIPO");
					this.OnTIPOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BALANCE", DbType="Money NOT NULL")]
		public decimal BALANCE
		{
			get
			{
				return this._BALANCE;
			}
			set
			{
				if ((this._BALANCE != value))
				{
					this.OnBALANCEChanging(value);
					this.SendPropertyChanging();
					this._BALANCE = value;
					this.SendPropertyChanged("BALANCE");
					this.OnBALANCEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="VarChar(200)")]
		public string USERNAME
		{
			get
			{
				return this._USERNAME;
			}
			set
			{
				if ((this._USERNAME != value))
				{
					this.OnUSERNAMEChanging(value);
					this.SendPropertyChanging();
					this._USERNAME = value;
					this.SendPropertyChanged("USERNAME");
					this.OnUSERNAMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
